__title__ = 'PAMtools'
__version__ = '1.0.0'
__license__ = 'MIT'
__author__ = 'Fabio D. Steffen'
__email__ = 'fabio.steffen@chem.uzh.ch'
__description__ = 'Visualization tools for PAM'
__keywords__ = 'PAM, FRET, TCSPC'
__url__ = 'https://github.com/fdsteffen/PAMtools'
__copyright__ = '2019 {}'.format(__author__)
